[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - LOGS_CAPTURED - Started capturing logs in process (pid: 85705).
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - start_kafka_producers - STEP_START - Started execution of step "start_kafka_producers".
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/crypto_producer.py
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/github_producer.py
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/weather_producer.py
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/crypto_producer.py': [Errno 2] No such file or directory
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - start_kafka_producers - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/github_producer.py': [Errno 2] No such file or directory
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - start_kafka_producers - Writing file at: /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/.tmp_dagster_home_nodshjkg/storage/start_kafka_producers using PickledObjectFilesystemIOManager...
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/weather_producer.py': [Errno 2] No such file or directory
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - start_kafka_producers - ASSET_MATERIALIZATION - Materialized value start_kafka_producers.
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - start_kafka_producers - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2025-08-20 10:54:15 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bdc9bc3d-0c9a-41c6-b18f-ea9182519bd5 - 85705 - start_kafka_producers - STEP_SUCCESS - Finished execution of step "start_kafka_producers" in 106ms.
