[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78874 - LOGS_CAPTURED - Started capturing logs in process (pid: 78874).
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78874 - developer_insights - STEP_START - Started execution of step "developer_insights".
/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/datastack_orchestration/assets.py:113: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78874 - developer_insights - STEP_FAILURE - Execution of step "developer_insights" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "developer_insights"::

OSError: Cannot save file into a non-existent directory: 'data'

Stack Trace:
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
        fn, context, kwargs, context_arg_provided, config_arg_class, resource_arg_mapping
    )
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/datastack_orchestration/assets.py", line 117, in developer_insights
    df.to_parquet('data/developer_insights.parquet')
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/core/frame.py", line 3118, in to_parquet
    return to_parquet(
        self,
    ...<6 lines>...
        **kwargs,
    )
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/io/parquet.py", line 482, in to_parquet
    impl.write(
    ~~~~~~~~~~^
        df,
        ^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/io/parquet.py", line 199, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ~~~~~~~~~~~~~~~~~~~^
        path,
        ^^^^^
    ...<3 lines>...
        is_dir=partition_cols is not None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/io/parquet.py", line 141, in _get_path_or_handle
    handles = get_handle(
        path_or_handle, mode, is_text=False, storage_options=storage_options
    )
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[0m
