[32m2025-08-20 10:03:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b2d6b8ae-3402-478e-8d1b-7323a5d5927e - 70132 - LOGS_CAPTURED - Started capturing logs in process (pid: 70132).
[32m2025-08-20 10:03:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b2d6b8ae-3402-478e-8d1b-7323a5d5927e - 70132 - data_quality_checks - STEP_START - Started execution of step "data_quality_checks".
[32m2025-08-20 10:03:47 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - b2d6b8ae-3402-478e-8d1b-7323a5d5927e - 70132 - data_quality_checks - STEP_FAILURE - Execution of step "data_quality_checks" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "data_quality_checks"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name raw_crypto_prices does not exist!
Did you mean "duckdb_types or pg_attribute"?

LINE 2:             SELECT COUNT(*) FROM raw_crypto_prices 
                                         ^

Stack Trace:
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
        fn, context, kwargs, context_arg_provided, config_arg_class, resource_arg_mapping
    )
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/datastack-env/lib/python3.13/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/datastack_orchestration/assets.py", line 141, in data_quality_checks
    result = conn.execute(query).fetchone()[0]
             ~~~~~~~~~~~~^^^^^^^
[0m
