[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - LOGS_CAPTURED - Started capturing logs in process (pid: 92366).
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - start_kafka_producers - STEP_START - Started execution of step "start_kafka_producers".
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mINFO[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/crypto_producer.py
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mINFO[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/github_producer.py
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mINFO[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - start_kafka_producers - Started: python3 /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/weather_producer.py
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/crypto_producer.py': [Errno 2] No such file or directory
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - start_kafka_producers - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - start_kafka_producers - Writing file at: /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/.tmp_dagster_home_cgk_pquc/storage/start_kafka_producers using PickledObjectFilesystemIOManager...
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/github_producer.py': [Errno 2] No such file or directory
/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/scripts/weather_producer.py': [Errno 2] No such file or directory
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - start_kafka_producers - ASSET_MATERIALIZATION - Materialized value start_kafka_producers.
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - start_kafka_producers - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2025-08-20 12:00:08 -0400[0m - dagster - [34mDEBUG[0m - kafka_producers_job - 12824c04-8768-4ba3-8f6e-e1050240b046 - 92366 - start_kafka_producers - STEP_SUCCESS - Finished execution of step "start_kafka_producers" in 73ms.
